baseurl: 'https://ventris.dev'
languageCode: en-us
title: "Braindump of ventris"
googleAnalytics: ""
disqusShortname: ""
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: true
pygmentsUseClasses: false
minify: true
paginate: 9999
disableKinds:
  - section
  - categories
  #- tags

permalinks:
  writing: /:year/:month/:day/:slug/

params:
  description: "hello there"

frontmatter:
  author: ventris
  github: ''
  og_image: 
  sitename: ventris
  twitter: ''

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed


